/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ObjectManipulation_MainActivity */

#ifndef _Included_com_example_ObjectManipulation_MainActivity
#define _Included_com_example_ObjectManipulation_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ObjectManipulation_MainActivity
 * Method:    GetObjectClassDemo
 * Signature: (Lcom/example/ObjectManipulation/Persion;)Lcom/example/ObjectManipulation/Persion;
 */
JNIEXPORT jobject JNICALL Java_com_example_ObjectManipulation_MainActivity_GetObjectClassDemo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_ObjectManipulation_MainActivity
 * Method:    IsInstanceOfDemo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ObjectManipulation_MainActivity_IsInstanceOfDemo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ObjectManipulation_MainActivity
 * Method:    AllocObjectDemo
 * Signature: ()Lcom/example/ObjectManipulation/Persion;
 */
JNIEXPORT jobject JNICALL Java_com_example_ObjectManipulation_MainActivity_AllocObjectDemo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ObjectManipulation_MainActivity
 * Method:    NewObjectDemo
 * Signature: (Ljava/lang/String;I)Lcom/example/ObjectManipulation/Persion;
 */
JNIEXPORT jobject JNICALL Java_com_example_ObjectManipulation_MainActivity_NewObjectDemo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_ObjectManipulation_MainActivity
 * Method:    NewObjectADemo
 * Signature: (Ljava/lang/String;I)Lcom/example/ObjectManipulation/Persion;
 */
JNIEXPORT jobject JNICALL Java_com_example_ObjectManipulation_MainActivity_NewObjectADemo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_ObjectManipulation_MainActivity
 * Method:    NewObjectVDemo
 * Signature: (Ljava/lang/String;I)Lcom/example/ObjectManipulation/Persion;
 */
JNIEXPORT jobject JNICALL Java_com_example_ObjectManipulation_MainActivity_NewObjectVDemo
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
